FROM haskell:latest

RUN apt-get update && apt-get install -y \
  libsqlite3-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /src/app

COPY . .

RUN stack setup && stack build

CMD ["stack", "exec", "your-bot-exe"]


